language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.3
  - 2.3.0
env:
  - RAILS_ENV=test
  - CODECLIMATE_REPO_TOKEN=75d1da76d5a205a703da8a9c13c7147bec4bd765dbb1195d85664f424b51cbf1
script:
  - bundle exec rspec
before_script:
  - bundle exec rake app:db:create
  - bundle exec rake app:db:schema:load
after_script:
  - bundle exec codeclimate-test-reporter
